const data = [
  {
    patents: [
      {
        path: "/state-art-search",
        heading: "STATE OF ART SEARCH",
        brief:
          "State of the art search involves exhaustive search, analysis, and synthesis of patent...",
        para: [
          "State of the art search involves exhaustive search, analysis, and synthesis of patent documents and specific publications relating to the technology domain of interest. The principal objective of a state of art search is to advise a client in evaluating the possible market possibilities for inventing the product or filing its patent. ",
          "It is also useful to understand potential competitors, identifying technology clumps, the potential improvisation in R&D for future prospective concerning others. ",
          "Our team provides extensive descriptions that incorporate the identified results and scenarios. We have subject matter experts for diverse technology domains.",
          "Our team conducts the Research in multiple databases in the patent database and non-patent literature coverage (journals, articles, scientific literature, product manuals, conference papers, video, image, and many more) around the World.",
          "In this process, All the searched references are manually analyzed, reviewed by a subject matter expert. To accomplish this, we utilize paid software for searching and preparing the best exhaustive report.",
        ],
        image: "/images/Patent/state-of-art-search.png",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
      },
      {
        path: "/freedom-to-operate-search",
        heading: "FREEDOM TO OPERATE SEARCH",
        brief: "Before launching a product in the market, there is always...",
        para: [
          "Before launching a product in the market, there is always a risk of being infringed by an already available patent. Freedom to operate search/ clearance search is used to analyze the product against an appropriate selection of patents to find out the level of risk associated with bringing the product to market. ",
          "Freedom to operate search/clearance search is geo-specific and particularly focuses on the claims of the granted patent. In our search strategy, we target granted patents while simultaneously including pending patent applications, as those may grant in the future can prove a threat to the client’s product. ",
          "We also make sure to include an analysis of WIPO patent applications that have the client’s specific geographical country as a designated country. Our freedom-to-operate/clearance search reports include an in-depth analysis of the claimed elements in the identified relevant prior-arts by our SME’s (subject matter experts). ",
        ],
        image: "/images/Patent/freedom-to-operate-search.png",
        list: [
          "Patentability/Novelty Searches",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
      },
      {
        path: "/prior-art-search",
        heading: "PRIOR ART SEARCH",
        brief:
          "Our Prior Art Searches and Analytics team uses creative and structured...",
        para: [
          "is also known as background art it’s defined as the pieces of evidence already available publicly before any specific or assigned date. Prior art searches is a dedicated search to recognize if there is any evidence that exists, that could believe a patent/application invalid. It can be categorized into three types, based on the purpose of the search, i.e. Novelty/Patentability Search, Medical/Chemical/Biological Searches,  Invalidity Search, and FTO Search.",
          "Our Prior Art Searches and Analytics team uses creative and structured processes and technologies for their domain to provide the best search reports.",
        ],
        image: "/images/Patent/design-image.png",
        list: [
          "Patentability / Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
          "Looking for Best IP Solutions",
        ],
        listPara: [
          "A complete history of search invention to make a unique strategy",
          "Search according to the strategy (multiple strategies)",
          "A short-list of references manually categorized and ranked for relevancy",
          "Tables highlighting relevant citations from the references",
          "Analytical charts and graphs to help you communicate with stakeholders",
          "Intuitive indicators of which inventive key features are disclosed, partially disclosed, or undisclosed",
        ],
      },
      {
        path: "/patent-drafting-illustrations",
        heading: "PATENT DRAFTING & ILLUSTRATIONS",
        brief: "A patent application needs to explain an invention entirely...",
        para: [
          "A patent application needs to explain an invention entirely. Patent Drafting Illustrations is the first and most essential step of the entire patent lifecycle. In this, it should be really clear that the invention is new and non-obvious, which means that heretofore it hasn’t existed. ",
          "Patent Drafting Illustrations is a process that combines technology and law.  Preparing these techno legal documents requires deep technology domain knowledge and must be adhered to certain criteria and standards of the Patent Law.",
          "A patent application needs to describe an invention completely such as Title of the invention, Summary of the invention, Abstract, Specifications, Claims, Detailed description of the drawings & Conclusion. Patent Application is a document through which an inventor discloses complete details of his invention and gets exclusive rights to it. ",
          "Our team assists clients in both provisional and non-provisional patent drafting support services in different technological domains",
        ],
        image: "/images/Patent/patent-drafting-illustrations.png",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
      },
      {
        path: "/chemical-structure-search",
        heading: "CHEMICAL STRUCTURE SEARCH",
        brief:
          "Some of the key tools we use for chemical structure searches...",
        para: [
          "is defined as the molecular geometry of a compound. In this search, we focus on finding a similar compound’s chemical structure search in patent and non-patent literature. This is basically conducted to evaluate Patentability, FTO, or validity/ invalidity of the structure. ",
          "Some of the key tools we use for chemical structure searches are – Scientific-Technical Networks (STN), Questel Orbit, SciFinder, ChemSpider, PubChem, WIPO and Sure ChEMBL, etc.  Additionally, our search methodology includes the study of distinctive property and behavior analysis, related background, typical usage, extensive class-based searches, assignee/inventor-based searches, etc.  ",
        ],
        image: "/images/Patent/chemical-structure-search.png",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
      },
      {
        path: "/patentability-novelty-searches",
        heading: "PATENTABILITY/NOVELTY SEARCHES",
        brief: "A patentability novelty search is also known as...",
        para: [
          "A patentability novelty search is also known as novelty search, is conducted before the filing of any patent application to check whether the invention is already available in the public domain. It is also useful for inventors, to know about the unique feature of their invention. This search ensures the inventor that the application won’t refuse during the examination.",
          "If some prior art is found during the search, the inventor either does not file the application and saves money or improvises the invention to file the application further. This patentability novelty search is conducted in different patent and non-patent databases such as written documents, utility models, products, and scientific literature.  ",
        ],
        image: "",
        list: [
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
          "Looking for Best IP Solutions",
        ],
        listPara: [],
      },
      {
        path: "/patent-landspace",
        brief:
          "A patent landscape is an analysis of patent data that exposes...",
        para: [
          "A patent landscape is an analysis of patent data that exposes business, scientific and technological trends. Landscape searches provide an opportunity for its analyst to evaluate the technology domain of interest from diverse viewing angles and zoom levels.",
          "Patent Landscape Whitespace Analysis is one of the key methods for strategic innovation & usually follows preliminary patent landscaping. ",
          "The Patent Landscape Whitespace Analysis is a survey of patents in a given technological area that seeks to answer one or more business objectives and scape reports typically focus on a single industry, technology, or geographic region. ",
          "By analyzing the patent holdings of competitors/ leading patent filers, their strategies and future products can be fairly identified. Therefore, it helps businesses to identify areas in which competitors/ leading patent filers may pose threat in the future and helps them to refine their strategies and identify possible areas for research and development (R&D). ",
          "We have experts in different technology domains, provide an exhaustive report to the client, which include: market trends, technology leaders, and their IP strategies, IP activity over the years organizing technology in a particular area, White space analysis for future research strategies.",
        ],
        image: "/images/Patent/patent-landscape.png",
        heading: "PATENT LANDSCAPE & WHITESPACE ANALYSIS",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Translation",
        ],
        listPara: [],
      },
    ],
  },
  {
    solutions: [
      {
        path: "/ip-firms",
        brief:
          "We Strengthen your Services with our vast Technology Expertise...",
        para: [
          "We Strengthen your Services with our vast Technology Expertise and IP or IP law firms experience – Get your Searches, Drafting, Proof Reading, Illustrations & more through with precise accuracy and speed from our Patent Scientists.",
          "We provide our services to attorneys and lawyers to support and serve their clients better in an efficient and timely manner. Intellectual property assets are one of the basic assets of any organization.",
          "So every organization needs attorney legal support – to file & prosecute their inventions, to litigate when their IP assets are challenged, and to monetize their property with no legal setback or compromise. To provide such legal support, an attorney needs to be investing his valuable time and energy in that specialize in every aspect of your client’s property needs.",
          "Day-by-Day IP is becoming more global and sophisticated. Handling every aspect of your clients’ IP needs is becoming a tedious & time-consuming process. We provide attorneys, our deep IP (IP law firms) & technology expertise, and supply you with ample information which will cater to your needs of patent prosecution, litigation, arbitration, acquisition, or licensing.",
          "Our team has technical expertise in altogether major fields. We consistently handle inventive matters involving hi-tech, electronics and electrical systems, technology, communication technologies, Robotics, AI, medical devices, consumer lifestyle, biotechnology, bioengineering, chemical, pharmaceutical, automobiles, energy, and mechanical systems.",
        ],
        specialPara: "Technical assistance to IP lawyers",
        image: "/images/Solutions/hammer-ip-firms.png",
        heading: "TO IP LAW FIRMS",
        listPara: [],
        secondListPara: [],
        spPara: "",
      },
      {
        path: "/technology-org",
        brief:
          "Services -Technology Landscapes & Insights, White space analysis...",
        para: [
          "Services -Technology Landscapes & Insights, White space analysis, FTO, Infringement Analysis, Rapid Novelty Searches, and IP Admin Services. Our firm has a decade of experience in handling technologies of varying complexities and performs comprehensive strategical property analysis.",
          "We combine information on changing industries, technologies, strategies with our in-depth understanding of IP to supply complete IP Lifecycle services starting from IP Creation, IP Prosecution to IP Monetization, IP Litigation, and IP Management. Strategically regulating TP with business plays an important role in the success of every technology company.",
          "Technology companies should create, protect, maintain and manage the property to remain before competitors to border an IP strategy that’s aligned to the business goals, it’s vital to get actionable intelligence by performing tedious analysis on thousands of technical documents including patents.",
          "Performing such tedious IP analysis is becoming more complex and demands a substantial amount of time and resources. We provide our services to Technology Giants, Medium & Small Enterprise also as Startups, and help to grow their businesses with IP assets. ",
        ],
        specialPara:
          "Intellectual property asserts are the growth of a company business and guarding them is the first step of success of a company.",
        image: "/images/Solutions/technology-org-image.png",
        heading: "TO TECHNOLOGY ORGANIZATIONS",
        listPara: [],
        secondListPara: [
          "Set your IP approaches straightened according to your business goals",
          "Compare your competitors IP activities",
          "Accomplish your IP portfolio to maximize Business value",
          "Develop IP trails worldwide",
          "Explore and Analyze upcoming technologies",
        ],
        spPara:
          "We provide Technology Organizations IP-Technology-Business Insights quickly and comprehensively so that you can: ",
      },
      {
        path: "/to-college-univ",
        brief:
          "College students always have new inventions and some futuristic ideas...",
        para: [
          "College students always have new inventions and some futuristic ideas. We provide our support to Colleges and Universities Patent Monetization Services, Licensing Support Services, Patent Searches, and Technology whitespace analysis. Make your Technology Transfer wing more productive with insights and support from us. We help university departments in patenting and also monetizing their IP assets.",
          "Even though the patenting activities in Academia are extremely minimal, there has been increased specialization in patenting academic inventions and licensing them to technology companies which reciprocally fetches revenue for academia.",
          "While Colleges and Universities are working to seek out solutions to problems as they arise, it might only be righteous if all of their inventions are patented and monetized. It’s well understood that patenting for academia has got to be done at a budget rate and that we clearly understand that and that we assist you to secure your patents in a cost-effective way.",
        ],
        specialPara:
          "Universities and academies are still behind in patenting their inventions and monetizing their patents, although they have innovative ideas and futuristic inventions",
        image: "/images/Solutions/to-college-univ-image.png",
        heading: "TO COLLEGES AND UNIVERTIES",
        listPara: [
          "Assist in cost-effective ways (initial assistance is completely free)",
          "Patent invention and help inventors to prepare the prototype",
          "Guide students for upcoming startup ventures",
        ],
        secondListPara: [],
        spPara: "",
      },
      {
        path: "/ip-consulting",
        brief:
          "We provide our help and assistance to otherIP consulting firms/companies...",
        para: [
          "We provide our help and assistance to otherIP consulting firms/companies in managing their IP projects, and to produce a variety of patent and technology analytical reports. We are here to make the patent and technology information research and analysis effortless for other firms.",
          "We have experience working with different IP consulting firms to giving them our expert services in requirements. Our team members have liaisoning with multiple IP firms and well-maintained relationships with top companies. We provide several types of supports to companies.",
        ],
        specialPara:
          "We provide our expertise to other IP firms related to client requirements.",
        image: "/images/Solutions/ip-consulting-image.png",
        heading: "TO IP CONSULTING FIRMS",
        listPara: [
          "Backend technological support in all kinds of searching and report preparation.",
          "Help to strive more domains and different expertise",
          "Domain-based expert searching",
          "Report formation and result selection",
          "Database assistance",
        ],
        secondListPara: [],
        spPara: "",
      },
      {
        path: "/copyright",
        brief:
          "Artistic, literary, or intellectually created works, such as novels, music...",
        para: [
          "Artistic, literary, or intellectually created works, such as novels, music, movies, software code, photographs, and paintings that are original and exist in a tangible medium, such as paper, canvas, film, or digital format. ",
          "Protects your exclusive right to reproduce, distribute, and perform or display the created work, and prevents other people from copying or exploiting the creation without the copyright holder’s permission.",
          "*Text from USPTO   Protect your artistic works with experts. ",
        ],
        specialPara: "",
        image: "/images/Solutions/copyright.png",
        heading: "COPYRIGHT",
        listPara: ["Copyright Filing", "Copyright Responses"],
        secondListPara: [],
        spPara: "",
      },
      {
        path: "/design",
        brief:
          "In a legal sense, an industrial design/Design Patent constitutes the ornamental aspect of an article...",
        para: [
          "In a legal sense, an industrial design/Design Patent constitutes the ornamental aspect of an article. An industrial design may consist of three-dimensional features, such as the shape of an article, or two-dimensional features, such as patterns, lines, or color.",
          "In principle, the owner of a registered industrial design or of a design patent has the right to prevent third parties from making, selling, or importing articles bearing or embodying a design that is a copy, or substantially a copy, of the protected design, when such acts are undertaken for commercial purposes.",
          "Industrial designs are applied to a wide variety of products of industry and handicraft items: from packages and containers to furnishing and household goods, from lighting equipment to jewelry, and from electronic devices to textiles. Industrial designs may also be relevant to graphic symbols, graphical user interfaces (GUI), and logos.",
          "In most countries, an industrial design needs to be registered in order to be protected under industrial design law as a “registered design”. In some countries, industrial designs are protected under patent law as “design patents”.",
          "Industrial design laws in some countries grant – without registration – time- and scope-limited protection to so-called “unregistered industrial designs”. Depending on the particular national law and the kind of design, industrial designs may also be protected as works of art under copyright law.",
          "*Text from WIPO File and protect your design with industry experts.",
        ],
        specialPara: "",
        image: "/images/Patent/design-image.png",
        heading: "DESIGN PATENT",
        listPara: [
          "Design Search",
          "Illustration",
          "Design Filing",
          "Examination Replies",
          "Response",
        ],
        secondListPara: [],
        spPara: "",
      },
    ],
  },
  {
    patentDoubleHeading : [
      {
        path: "/patent-translation",
        brief:
          "An inventor/applicant always wants the complete benefits...",
        heading: "PATENT TRANSLATION",
        secHeading: "WHY WE?",
        para: [
          "An inventor/applicant always wants the complete benefits of his invention worldwide. To file the patent in every jurisdiction needs the patent in the jurisdiction language. It is not just translating the invention in the other language but also making it correct in the form of that language. ",
          "Nowadays, there are multiple tools and software are available for patent translation that make it easy to translate any word in any language. But every invention contains all the technical definition in it, which make any tool hard to translate. ",
          "A machine translation done by the tool can make a huge difference in its original sense. In machine translation, errors are not limited to a single word but they can even alter the understanding of large excerpts.",
        ],
        image: "/images/Patent/patent-translation.png",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
        ],
        listPara: [],
        secondPara: [
          "Even if we do a human translation, the invention carries technical things. The human translation only can be done correctly if the translator knows technology and legal. Oohr Intellectual Research has native language persons with expertise and experience in technology and legal. ",
          "We provide language translation services in Chinese, Japanese, Korean patents. In addition to providing patent translation services, we prepare patent applications in compliance with specific jurisdiction protocols. ",
          "A strict legal commitment to information security and confidentiality is applied to every step of the patent translation process to guarantee that your documents remain private.  Linguistic quality assurance is provided by the application of linguistic quality analysis to measure and certify the accuracy of each patent translation.",
        ],
      },
      {
        path: "/patent-filing-service",
        brief:
          "To get the protection of the inventor’s unique invention...",
        heading: "PATENT FILING SERVICE",
        secHeading: "WHY WE?",
        para: [
          "To get the protection of the inventor’s unique invention, it needs to file in the best manner so the inventor can get its benefits. Patent filing service is a complicated process, in which the applicant/Inventor may need proper assistance from experienced attorneys and experts.",
          "Oohr Intellectual Research has a well-experienced team of USA patent attorneys and Indian patent agents, who always help clients to file their patents most suitable manner. Right now we are only providing patent filing services in the USA and India.",
        ],
        image: "/images/Patent/patent-filing-service.png",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Analysis & Claim Charts",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
        secondPara: [
          "Filing patent needs techno-legal knowledge, incorrectly completed procedures and forms may result in the loss of a significant right. It also may delay in priority date.",
          "Even after application filing and submission, there are still many other documents that need to be submitted within the stipulated timeframes. Lack of a deadline for such submissions may result in the revocation of the patent and provide time and money invested as a waste. With expert knowledge and experience, we take care of the complete filing process and give entire support to clients and inventions. ",
        ],
      },
      {
        path: "/office-action-response",
        brief:
          "An inventor/applicant gets a granted patent after go-through...",
        heading: "OFFICE ACTION RESPONSE",
        secHeading: "WHY WE?",
        para: [
          "An inventor/applicant gets a granted patent after go-through multiple examinations after filing the patent application.  Once a patent application (Non-provisional) is filed, the patent examiner explores for already available prior art of the filled invention and also notices various other irregularities in the patent/filing documents, etc., based on which the Examiner gives a response to the inventor/applicant. ",
          "An answer by the inventor/applicant to the examiner’s response over the objection or rejections knows as an office action response. It is the responsibility of the inventor/applicant to convince the examiner, either with arguments or with necessary amendments in the filed patent application claims during an Office Action Response. ",
        ],
        image: "",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
        secondPara: [
          "Drafting of an office action response is a process that may decide the future of the invention. A wrong draft or faulty response can lead to the incorrect mode of the invention. With this the inventor/ applicant, not just loses the benefits of the patent but also can get permanent rejection over there, or also may get the narrow claim. ",
          "With the help of highly skilled and experienced techno-legal professionals, Oohr Intellectual Research helps inventors/applicants in drafting rigid and best responses. We provide the office action response service to patents filed across various jurisdictions including the US, India, Europe, Kuwait, Australia, and other Asian countries. Our team has extensive experience in not only drafting superior responses but also in assisting attorneys in negotiating the scope with examiners in examiner interviews, to ensure that the finally allowed claim set is not too narrow. ",
        ],
      },
      {
        path: "/patent-validity-invalidity-searches",
        brief:
          "is a comprehensive prior art search. It’s conducted after the issuance of...",
        heading: "PATENT VALIDITY / INVALIDITY SEARCHES",
        secHeading: "HOW WE ASSIST",
        para: [
          "is a comprehensive prior art search. It’s conducted after the issuance of a patent either to authenticate the enforceability of a patent’s claims or to revoke claims of a patent.",
          "In this, a search is performed to identify patent or non-patent literature filed or published before the earliest priority date of the subject patent. The search serves as a basis for a legal opinion against infringement or as due diligence prior to licensing, buying, or selling of a patent. ",
        ],
        image: "",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Drawings",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
        secondPara: [
          "Our team conducts the Research in multiple databases in the patent database and non-patent literature coverage (journals, articles, scientific literature, product manuals, conference papers, video, image, and many more) around the World.",
          "In this process, All the searched references are manually analyzed, reviewed by a subject matter expert. To accomplish this, we utilize paid software for searching and preparing the best exhaustive report. ",
        ],
      },
      {
        path: "/patent-utility-design-drawings",     
        brief:
          "Utility Patent drawings or Utility Patent Illustrations...",
        heading: "UTILITY PATENT DRAWINGS",
        secHeading: "DESIGN PATENT DRAWINGS",
        para: [
          "Utility Patent drawings or Utility Patent Illustrations are one of the most essential elements of a patent application which representations graphically of an inventive idea submitted by the patent application before the patent office. Utility Patent Drawings typically show parts of a device, assemblies, electric circuits, components of a system, or a flow chart of a process whichever is claimed in Patent.  ",
        ],
        image: "/images/Patent/patent-utility-design-drawings.png",
        list: [
          "Patentability/Novelty Searches",
          "Freedom to Operate Search",
          "Patent Validity or Invalidity Search",
          "State of the Art Search",
          "Chemical Structure Search",
          "Biological Sequence Search",
          "Patent Drafting & Illustrations",
          "Office Action Response",
          "Patent Maintenance",
          "Infringement Analysis & Claim Charts",
          "Patent Filing Service",
          "Patent Landscape & Whitespace Analysis",
          "Patent Translation",
        ],
        listPara: [],
        secondPara: [
          "Design Patent Drawings assist you in protecting the structural and ornamental representation of your inventive idea. It doesn’t protect the functions of your invention. In the Design Patent application, the drawings themselves are the claims.",
          "The drawings must be prepared as the Patent Law to meet the requirements of the country, where the patent is filed such as the United State Patent and Trademark Office (USPTO), EPO, CHINA, ARIPO, South Korea, Indian Patent Office, or any other jurisdictions. ",
          "To prepare High-Quality drawings you need Drawing Engineer, who is well-versed in the legal and technical field to prepare the best drawings as per your need. Our engineers can prepare Utility Patent Drawing, Design Patent Drawing, Objected Drawing, and PCT Drawing & Trademark Drawing have significant experience with IP in medicine, mechanical and electrical engineering, high-tech, biotechnology, and chemistry or other industries. ",
        ],
      },
    ]
  },
];

export default data;